language: rust
rust:
  - 1.28.0
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

# Use Travis container-based system (much faster to start up)
sudo: false
